// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkof9Lr5fCmATaEUY0emfktpczcNgBv0',
    appId: '1:795119446957:web:e04f676cf156d586fb0f24',
    messagingSenderId: '795119446957',
    projectId: 'book-warm-boutique',
    authDomain: 'book-warm-boutique.firebaseapp.com',
    storageBucket: 'book-warm-boutique.appspot.com',
    measurementId: 'G-5WQS4CLXKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbljfhBqNaoAYhKAVTikDt-94HqgoxcV0',
    appId: '1:795119446957:android:ab786eb1cdbfc871fb0f24',
    messagingSenderId: '795119446957',
    projectId: 'book-warm-boutique',
    storageBucket: 'book-warm-boutique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiTLADAr52rzze8hKAoEn9UksgRww1njY',
    appId: '1:795119446957:ios:2acf39c597b60641fb0f24',
    messagingSenderId: '795119446957',
    projectId: 'book-warm-boutique',
    storageBucket: 'book-warm-boutique.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );
}
